version: '2'
services:
  db:
    image: postgres:8.4.22
    environment:
      POSTGRES_DB: pyconjp2016
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    #volumes:
    #  - ./vol/db:/var/lib/postgresql/data
  web:
    build: .
    image: pyconjp/website:2016
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - db:postgres
    environment:
      DEBUG: 1
      ENVIRONMENT: dev
      DB_ENGINE: postgresql_psycopg2
      DB_NAME: pyconjp2016
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_HOST: postgres
      DB_PORT: 5432
      LOG_PATH: ./pyconjp_website.log
      ERROR_LOG_PATH: ./pyconjp_website.error.log
      SECRET_KEY: "<secret>"
      LANG: ja_JP.UTF-8
    volumes:
      - .:/app

